
set guifont=RobotoMono\ Nerd\ Font\ Regular\ 10

syntax on
let g:gruvbox_number_column='bg1'
colorscheme gruvbox
set t_Co=256
set background=dark

set number
set wildmenu
set cursorline
set ignorecase
set smartcase

" highlight extra whitespace at the end
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
au ColorScheme * highlight ExtraWhitespace guibg=red
au BufEnter * match ExtraWhitespace /\s\+$/
au InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
au InsertLeave * match ExtraWhiteSpace /\s\+$/

" highlight last inserted text
nnoremap gV `[v`]

" for pgup and pgdown to work as usual
nnoremap <silent> <PageUp> <C-U><C-U>
vnoremap <silent> <PageUp> <C-U><C-U>
inoremap <silent> <PageUp> <C-\><C-O><C-U><C-\><C-O><C-U>

nnoremap <silent> <PageDown> <C-D><C-D>
vnoremap <silent> <PageDown> <C-D><C-D>
inoremap <silent> <PageDown> <C-\><C-O><C-D><C-\><C-O><C-D>

" tabs navigation (Ctrl-t opens tab; Ctrl-h,-j move to left,right tabs)
nmap <C-h> :tabprevious<CR>
nmap <C-l> :tabnext<CR>
nmap <C-t> :tabnew<CR>

"show tree in vim vinegar
let g:netrw_liststyle = 3

"remove all trailing whitespace by pressing F8
nnoremap <F8> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>

" stuff for python PIP8
au BufNewFile,BufRead *.py set
    \ tabstop=4
    \ softtabstop=4
    \ shiftwidth=4
    \ textwidth=79
    \ expandtab
    \ autoindent
    \ fileformat=unix
