---
#customize the environment of the local user
- hosts: localhost
  tasks:

  - name: Clone dotfiles repo
    git:
      repo: 'https://github.com/arielzn/dotfiles.git'
      dest: /tmp/dotfiles

  - name: Copy powerbash.sh script
    copy:
      src: /tmp/dotfiles/.powerbash.sh
      dest: ~/.powerbash.sh
      remote_src: yes

  - name: Setup custom tmux.conf
    copy:
      src: /tmp/dotfiles/.tmux.conf
      dest: ~/.tmux.conf
      remote_src: yes

  - name: Customize bash
    lineinfile:
      dest: ~/.bashrc
      line: "{{ item }}"
    with_items:
      - "alias ls='ls --color=auto'"
      - "alias ll='ls -alFh'"
      - "alias la='ls -A'"
      - "export HISTSIZE=50000"
      - "source ~/.powerbash.sh"
      - "powerbash host on"
      - "powerbash path full"
      - "powerbash hg off"

  - name: Force an emtpy ~/.vim
    file:
      path: ~/.vim
      state: absent

  - name: Move vim dotfiles to ~/.vim
    command: cp -r /tmp/dotfiles/.vim ~/

  - name: Clone Vundle for vim
    git:
      repo: 'https://github.com/VundleVim/Vundle.vim.git'
      dest: ~/.vim/bundle/Vundle.vim

  - name: Insert Vundle configuration in ~/.vim/vimrc
    blockinfile:
      insertbefore: BOF
      marker: '" {mark} Vundle plugin manager setup'
      path: ~/.vim/vimrc
      block: |
        set nocompatible
        filetype off

        " set the runtime path to include Vundle and initialize
        set rtp+=~/.vim/bundle/Vundle.vim
        call vundle#begin()

        Plugin 'tpope/vim-vinegar'
        Plugin 'vim-airline/vim-airline'
        Plugin 'vim-airline/vim-airline-themes'
        Plugin 'nvie/vim-flake8'
        Plugin 'lervag/vimtex'
        Plugin 'airblade/vim-gitgutter'

        " All the Plugins must be added before the following line
        call vundle#end()
        filetype plugin indent on

        let g:airline_powerline_fonts = 1

  - name: Install plugins
    command: vim +PluginInstall +qall
