---

- hosts: localhost
  tasks:

  - name: Customize pacman.conf
    lineinfile:
      dest: /etc/pacman.conf
      regexp: Color
      line: 'Color'

  - name: Customize environment
    lineinfile:
      dest: /etc/environment
      line: "{{ item }}"
    with_items:
      - "GVIM_ENABLE_WAYLAND=1"

  - name: Install Intel GPU drivers
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - libva-intel-driver
      - intel-gpu-tools
      #      - libva-utils
      #      - libvdpau-va-gl
      #      - vdpauinfo

  - name: Install basic tools
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - base-devel
      - bash
      - bash-completion
      - binutils
      - dmidecode
      - expac
      - git
      - htop
      - iw
      - mlocate
      - pacman-contrib
      - chrony
      - lshw
      - usbutils
      - p7zip
      - tmux
      - pwgen
      - man-db
      - fwupd
      - wget
      - smartmontools
      - sof-firmware
      - tlp

  - name: Install Gnome DE
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - arc-gtk-theme
      - arc-icon-theme
      - pipewire
      - pipewire-jack
      - gnome
      - gnome-tweaks
      - eog
      - file-roller
      - gucharmap
      - gvim
      - archlinux-appstream-data
      - gnome-shell-extension-appindicator
      - networkmanager
      - networkmanager-openconnect
      - networkmanager-openvpn

  - name: Install sway wm
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - sway
      - foot
      - wmenu
      - swaylock
      - swayidle
      - swaybg

  - name: Install extra stuff
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - firefox
      - thunderbird
      - chromium
      - gimp
      - libreoffice-fresh
      - vlc
      - keepassxc
      - ttf-roboto
      - ttf-roboto-mono-nerd

  - name: Install pikaur deps
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - pyalpm
      - python-wheel
      - python-hatchling
      - python-build
      - python-installer
      - python-setuptools
      - python-markdown-it-py

  - name: Get pikaur aur helper sources
    get_url:
      url: "https://aur.archlinux.org/cgit/aur.git/snapshot/{{ item }}"
      dest: "/tmp/{{ item }}"
    with_items:
      - pikaur.tar.gz

  - name: Insert global vim options in /etc/vimrc
    blockinfile:
      insertbefore: EOF
      marker: '" {mark} Ansible managed set basic vim options'
      path: /etc/vimrc
      block: |
        syntax on
        colorscheme koehler
        set t_Co=256
        set number
        set wildmenu
        set cursorline
        set ignorecase
        set smartcase

  - name: Ensure critical services are enabled
    service:
      name: "{{ item }}"
      enabled: "yes"
    with_items:
      - chronyd
      - gdm
      - NetworkManager
      - bluetooth
      - tlp
